### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by jebu75** [Esri/maps-app-javascript#8]
The npm start command errors on windows 7.  I've installed the latest version of node and the windows build tools, ran the npm install command on a fresh clone of the repo.

## Description

Error details:

```
Error: The system cannot find the path specified.

    at notFoundError (E:\webstorm-projects\maps-app-javascript-base\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (E:\webstorm-projects\maps-app-javascript-base\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (E:\webstorm-projects\maps-app-javascript-base\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

I don't believe this to be a bug.  Looking for pointers on resolving this to get dev environment working.  Thanks!

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by jebu75** [comment]
I started over and re-cloned and it appears to be working now.
