### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by aventham** [Esri/maps-app-javascript#9]
## Description

maps-app-javascript\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.5.5-win32-x64.tar.gz failed: tunneling socket could not be established, statusCode=403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

## Actual Behaviour
Installation fails at this point; I can download the .gz file but don't know what to do with it manually.

## Steps to Reproduce
npm install (after having successfully installed the Windows build tools pre-requisite)

## Context
Unable to install

## Your Environment
Windows 10 Pro PC with latest 64-bit versions of node.js and git

**Comment by aventham** [comment]
Error messages continue as follows:

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Work\AV\js_apps\maps-app-javascript-master\maps-app-javascript\node_modules\sharp
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN rollback Rolling back ajv@4.11.8 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\Work\AV\js_apps\maps-app-javascript-master\maps-app-javascript\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back node-pre-gyp@0.6.39 failed (this is probably harmless): EPERM: operation not permitted, lstat 'c:\Work\AV\js_apps\maps-app-javascript-master\maps-app-javascript\node_modules\fsevents\node_modules'
npm WARN @theintern/istanbul-loader@1.0.0-beta.1 requires a peer of webpack@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN maps-app-javascript@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Temp\npmcache\_logs\2018-06-13T09_06_07_953Z-debug.log

**Comment by aventham** [comment]
I have reproduced the above error with the command "npm install sharp" so will close this issue as it is clearly specific to the dependency.
